site_name: 个人文档

theme: material
plugins:
  - markmap

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 首页: index.md
  - go:
      - 操作文档: go/搭建环境.md
      - 配置文件: go/config.md
      - 连接pysql: go/mysql.md
      - 连接redis: go/redis.md
      - swagger文档生成: go/swagger.md
  - togds:
      - 架构: togds/index.md
      - 数据库表设计: togds/数据库设计.md